before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/docurift
    binary: docurift
    dir: .
    ldflags:
      - -s -w
      - -X github.com/tienanr/docurift/cmd/docurift.version={{.Version}}
      - -X github.com/tienanr/docurift/cmd/docurift.commit={{.ShortCommit}}
      - -X github.com/tienanr/docurift/cmd/docurift.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - config.yaml
      - examples/

dockers:
  - image_templates:
      - "ghcr.io/tienanr/docurift:{{ .Version }}"
      - "ghcr.io/tienanr/docurift:latest"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - config.yaml
      - go.mod
      - go.sum
      - cmd/
      - internal/

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch 