proxy:
    port: 9876
    backend-url: http://host.docker.internal:8080

analyzer:
    port: 9877
    max-examples: 10
    redacted-fields:
        - Authorization
        - api_key
        - password
    storage:
        path: /etc/docurift/
        frequency: 10