name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./internal/... -v

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: |
          go tool $HOME/go/bin/staticcheck ./internal/... ./cmd/...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose Tests
        run: |
          if [ ! -d "test" ]; then
            echo "Error: test directory not found"
            exit 1
          fi
          cd test
          docker compose up --build test --exit-code-from test
